name: do_an_ngon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  bloc: ^9.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  logger: ^2.6.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  qr_flutter: ^4.1.0
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  animations: ^2.0.11
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  audioplayers: ^6.5.0
  azlistview: ^2.0.0
  google_mlkit_barcode_scanning: ^0.14.1
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  top_snackbar_flutter: ^3.3.0
  flutter_dash: ^1.0.0
  flutter_cached_pdfview: ^0.4.3
  url_launcher: ^6.2.5
  fl_chart: ^1.0.0
  flutter_html: ^3.0.0
  share_plus: ^11.1.0
  path_provider: ^2.1.2
  device_info_plus: ^9.1.2
  image_gallery_saver_plus: ^4.0.1
  open_filex: ^4.7.0
  dropdown_button2: ^2.3.9
  flutter_blue_plus: ^1.31.0
  blue_thermal_printer: ^1.2.3
  #  esc_pos_printer: ^4.1.0
  #  esc_pos_utils: ^1.1.0

  lottie: ^3.3.0
  screenshot: ^3.0.0
  package_info_plus: ^8.3.0
  firebase_core: ^4.2.0
  firebase_remote_config: ^6.1.0
  sentry_flutter: ^9.7.0
  change_app_package_name: ^1.5.0
  shadcn_ui: ^0.27.1
  esc_pos_utils_plus: ^2.0.4
  esc_pos_printer_plus: ^0.1.1
  flutter_launcher_icons: ^0.14.4
  easy_rich_text: ^2.2.0
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  flutter_gen_runner: ^5.11.0
  intl_utils: ^2.8.11

dependency_overrides:
  intl: ^0.20.2

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/animes/
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Regular.ttf
          weight: 400
        - asset: assets/fonts/Philosopher-Italic.ttf
          weight: 500
        - asset: assets/fonts/Philosopher-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/src/resources/generated

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  main_locale: vi
  output_dir: lib/src/resources/generated
  arb_dir: lib/src/resources/l10n

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_icon_insure_noalpha.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/app_icon_insure_noalpha.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#ffffff"
    image: assets/png/app_icon_insure_noalpha.png
